# src/backtesting/parquet_loader.py

"""
Parquet data loader for backtesting and replay.

Loads tick data from Parquet files (generated by record_live_data.py) and
converts them into HistoricalDataset objects compatible with BacktestEngine.

Architecture:
    Parquet files (partitioned by asset/date)
        → read_ticks_uniform()  (schema normalisation)
        → MarketTick conversion
        → HistoricalDataset

Usage:
    loader = ParquetDataLoader(base_dir="data/parquet")
    dataset = loader.load(asset="BTC", market_id="0xabc...")
    # or
    datasets = loader.load_all(asset="BTC")  # all BTC markets

Dependencies:
    - src.infrastructure.data.schema.read_ticks_uniform
    - src.backtesting.data_loader.HistoricalDataset
    - src.domain.value_objects.market_tick.MarketTick
"""

from datetime import datetime, timezone
from glob import glob
from pathlib import Path
from typing import Optional

import pyarrow as pa
import structlog

from src.backtesting.data_loader import HistoricalDataset
from src.domain.value_objects.market_tick import MarketTick
from src.infrastructure.data.schema import (
    TICK_SCHEMA,
    read_ticks_uniform,
)

logger = structlog.get_logger(__name__)

# Default window label for Parquet-sourced data.
# Parquet data is raw tick data — no aggregation window applied.
# The user specifies the window context when loading.
DEFAULT_WINDOW = "5m"


class ParquetDataLoader:
    """
    Load tick data from Parquet files into HistoricalDataset objects.

    Handles:
    - Partitioned Parquet directories (asset=BTC/year=2026/month=05/day=27/)
    - Schema normalisation (dictionary<string> vs plain string)
    - Filtering by asset, market_id, date range
    - Conversion from Parquet rows → MarketTick domain objects

    The Parquet schema uses nanosecond timestamps (timestamp_ns) and
    stores prices as float64 with 4-decimal precision.
    """

    def __init__(self, base_dir: str | Path = "data/parquet"):
        self._base_dir = Path(base_dir)
        if not self._base_dir.exists():
            logger.warning("parquet_base_dir_missing",
                           path=str(self._base_dir))

    # ── Public API ─────────────────────────────────────────────────────────

    def load(
        self,
        asset: str,
        market_id: Optional[str] = None,
        window: str = DEFAULT_WINDOW,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
    ) -> HistoricalDataset:
        """
        Load ticks for a specific asset and optionally a specific market.

        Args:
            asset: "BTC" or "ETH"
            market_id: Specific condition_id (0x...) to filter by.
                       If None, loads all markets for the asset.
            window: Label for the dataset window (default: "raw").
            start_date: Inclusive UTC start date filter.
            end_date: Exclusive UTC end date filter.

        Returns:
            HistoricalDataset with ticks sorted by timestamp_ns.
        """
        paths = self._find_parquet_files(asset, start_date, end_date)

        if not paths:
            raise FileNotFoundError(
                f"No Parquet files found for asset={asset} "
                f"in {self._base_dir}"
            )

        logger.info("parquet_load_start",
                     asset=asset,
                     market_id=market_id,
                     files=len(paths))

        # Read and normalize all Parquet files into a single table
        table = read_ticks_uniform(paths, schema=TICK_SCHEMA)

        if table.num_rows == 0:
            raise ValueError(
                f"No tick data found in {len(paths)} Parquet files "
                f"for asset={asset}"
            )

        # Filter by market_id if specified
        if market_id:
            import pyarrow.compute as pc  # type: ignore[attr-defined]  # pc.equal/pc.unique not in stubs
            mask = pc.equal(table.column("market_id"), market_id)  # type: ignore[attr-defined]
            table = table.filter(mask)
            if table.num_rows == 0:
                raise ValueError(
                    f"No ticks found for market_id={market_id[:20]}..."
                )

        # Convert to MarketTick objects
        ticks = self._table_to_ticks(table)

        logger.info("parquet_load_complete",
                     asset=asset,
                     ticks=len(ticks),
                     files=len(paths),
                     start=ticks[0].timestamp.isoformat() if ticks else None,
                     end=ticks[-1].timestamp.isoformat() if ticks else None)

        return HistoricalDataset(
            asset=asset,
            window=window,
            market_id=market_id or f"parquet_{asset}",
            ticks=ticks,
            start_at=ticks[0].timestamp,
            end_at=ticks[-1].timestamp,
        )

    def load_all(
        self,
        asset: str,
        window: str = DEFAULT_WINDOW,
    ) -> list[HistoricalDataset]:
        """
        Load all markets for an asset as separate HistoricalDatasets.

        Useful for backtesting individual markets independently.
        """
        paths = self._find_parquet_files(asset)

        if not paths:
            return []

        table = read_ticks_uniform(paths, schema=TICK_SCHEMA)

        # Group by market_id
        import pyarrow.compute as pc  # type: ignore[attr-defined]  # pc not in stubs
        market_ids = pc.unique(table.column("market_id")).to_pylist()  # type: ignore[attr-defined]

        datasets = []
        for mid in market_ids:
            mask = pc.equal(table.column("market_id"), mid)  # type: ignore[attr-defined]
            subtable = table.filter(mask)
            ticks = self._table_to_ticks(subtable)
            datasets.append(HistoricalDataset(
                asset=asset,
                window=window,
                market_id=mid,
                ticks=ticks,
                start_at=ticks[0].timestamp,
                end_at=ticks[-1].timestamp,
            ))

        logger.info("parquet_load_all",
                     asset=asset,
                     markets=len(datasets),
                     total_ticks=sum(d.tick_count for d in datasets))

        return datasets

    def list_markets(self, asset: str) -> list[str]:
        """List all unique market_ids for an asset in the Parquet data."""
        paths = self._find_parquet_files(asset)
        if not paths:
            return []

        table = read_ticks_uniform(paths, schema=TICK_SCHEMA)
        import pyarrow.compute as pc  # type: ignore[attr-defined]  # pc not in stubs
        return sorted(pc.unique(table.column("market_id")).to_pylist())  # type: ignore[attr-defined]

    def get_tick_count(self, asset: str) -> int:
        """Get total tick count for an asset."""
        paths = self._find_parquet_files(asset)
        if not paths:
            return 0

        table = read_ticks_uniform(paths, schema=TICK_SCHEMA)
        return table.num_rows

    def get_date_range(
        self, asset: str
    ) -> tuple[datetime, datetime] | None:
        """Get the min/max timestamp range for an asset."""
        paths = self._find_parquet_files(asset)
        if not paths:
            return None

        table = read_ticks_uniform(paths, schema=TICK_SCHEMA)
        import pyarrow.compute as pc  # type: ignore[attr-defined]  # pc not in stubs

        min_ns = pc.min(table.column("timestamp_ns")).as_py()  # type: ignore[attr-defined]
        max_ns = pc.max(table.column("timestamp_ns")).as_py()  # type: ignore[attr-defined]

        min_dt = datetime.fromtimestamp(min_ns / 1_000_000_000, tz=timezone.utc)
        max_dt = datetime.fromtimestamp(max_ns / 1_000_000_000, tz=timezone.utc)

        return min_dt, max_dt

    # ── Internal ───────────────────────────────────────────────────────────

    def _find_parquet_files(
        self,
        asset: str,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
    ) -> list[str]:
        """Find all .parquet files for an asset, optionally filtered by date."""
        asset_dir = self._base_dir / f"asset={asset}"

        if not asset_dir.exists():
            return []

        pattern = str(asset_dir / "**" / "*.parquet")
        paths = sorted(glob(pattern, recursive=True))

        if not paths:
            return paths

        # Filter by date range using the Hive-style partition structure
        if start_date or end_date:
            filtered = []
            for p in paths:
                path = Path(p)
                # Extract year/month/day from partition path:
                # .../asset=BTC/year=2026/month=05/day=27/ticks_....parquet
                parts = path.parts
                try:
                    year_idx = next(
                        i for i, part in enumerate(parts)
                        if part.startswith("year=")
                    )
                    month_idx = year_idx + 1
                    day_idx = year_idx + 2

                    year = int(parts[year_idx].split("=")[1])
                    month = int(parts[month_idx].split("=")[1])
                    day = int(parts[day_idx].split("=")[1])

                    file_date = datetime(year, month, day, tzinfo=timezone.utc)

                    if start_date and file_date < start_date.replace(
                        hour=0, minute=0, second=0, microsecond=0
                    ):
                        continue
                    if end_date and file_date >= end_date.replace(
                        hour=0, minute=0, second=0, microsecond=0
                    ):
                        continue

                    filtered.append(p)
                except (StopIteration, IndexError, ValueError):
                    # If partition structure is unexpected, include the file
                    filtered.append(p)
            return filtered

        return paths

    @staticmethod
    def _table_to_ticks(table: pa.Table) -> list[MarketTick]:
        """Convert a PyArrow Table to a list of MarketTick domain objects."""
        ticks = []

        # Extract columns as Python lists for fast iteration
        timestamps = table.column("timestamp_ns").to_pylist()
        market_ids = table.column("market_id").to_pylist()
        yes_prices = table.column("yes_price").to_pylist()
        no_prices = table.column("no_price").to_pylist()
        best_bids = table.column("best_bid").to_pylist()
        best_asks = table.column("best_ask").to_pylist()
        spreads = table.column("spread").to_pylist()
        volumes = table.column("volume_24h").to_pylist()

        for i in range(table.num_rows):
            ts_ns = timestamps[i]
            ts_dt = datetime.fromtimestamp(
                ts_ns / 1_000_000_000, tz=timezone.utc
            )

            ticks.append(MarketTick(
                market_id=market_ids[i],
                yes_price=round(yes_prices[i], 4),
                no_price=round(no_prices[i], 4),
                best_bid=round(best_bids[i], 4),
                best_ask=round(best_asks[i], 4),
                spread=round(spreads[i], 4),
                volume_24h=round(volumes[i], 2),
                timestamp=ts_dt,
            ))

        return ticks
