#!/usr/bin/env python3
# scripts/analyze_post_trade.py
"""
Post-Trade Analytics CLI — Fase 10.4 DESPLEGAR.

Run PostTradeAnalyzer on backtest results to generate detailed
performance attribution reports (expectancy, profit factor,
exit-reason breakdown, streaks, drawdown, Sharpe estimate).

Usage:
    # From a backtest metrics JSON file (generated by BacktestReporter.save())
    python scripts/analyze_post_trade.py \\
        --input results_metrics.json

    # From a trades CSV file (generated by BacktestReporter.save())
    python scripts/analyze_post_trade.py \\
        --input results_trades.csv --balance 1000

    # Output to custom file with asset/window labels
    python scripts/analyze_post_trade.py \\
        --input results.json --output analysis.json \\
        --asset BTC --window 5m
"""

import argparse
import csv
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.quantitative.post_trade import PostTradeAnalyzer


@dataclass
class FakePosition:
    """Duck-typed position for the analyzer (matches BacktestPosition interface)."""

    pnl: float | None
    exit_reason: str | None = None
    entry_tick: int | None = None
    exit_tick: int | None = None
    amount: float = 10.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Post-Trade Analytics — Fase 10.4",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/analyze_post_trade.py --input results_metrics.json
  python scripts/analyze_post_trade.py --input results_trades.csv --balance 1000
  python scripts/analyze_post_trade.py --input results.json --output analysis.json
        """,
    )
    parser.add_argument(
        "--input", "-i",
        help="Path to backtest metrics JSON or trades CSV",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output path for post-trade report JSON (default: stdout)",
    )
    parser.add_argument(
        "--balance", "-b",
        type=float,
        default=1000.0,
        help="Initial balance for PnL percentages (default: 1000.0)",
    )
    parser.add_argument(
        "--asset",
        default=None,
        help="Asset label for the report header (e.g., BTC, ETH)",
    )
    parser.add_argument(
        "--window",
        default=None,
        help="Window label for the report header (e.g., 5m, 15m)",
    )
    return parser.parse_args()


def load_from_json(path: str) -> list[FakePosition]:
    """Load positions from a backtest metrics JSON file.

    The JSON format matches BacktestReporter._save_json():
      { "trades": [ { "pnl": ..., "exit_reason": ... }, ... ] }
    """
    with open(path) as f:
        data = json.load(f)

    # BacktestReporter metrics JSON — per-trade data in top-level "trades"
    trades = data.get("trades", [])
    if trades:
        return [
            FakePosition(
                pnl=t.get("pnl"),
                exit_reason=t.get("exit_reason"),
                entry_tick=t.get("entry_tick"),
                exit_tick=t.get("exit_tick"),
                amount=t.get("amount", 10.0),
            )
            for t in trades
        ]

    # PostTradeAnalyzer report JSON (re-analysis) — has post_trade key
    pt_data = data.get("post_trade", {})
    if pt_data:
        print(
            "⚠️  Input is already a post-trade report."
            " Run on original metrics JSON.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("❌ No 'trades' array found in JSON.", file=sys.stderr)
    sys.exit(1)


def load_from_csv(path: str) -> list[FakePosition]:
    """Load positions from a backtest trades CSV file.

    The CSV format matches BacktestReporter._save_csv():
      pnl, exit_reason, entry_tick, exit_tick, amount, ...
    """
    positions = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pnl_str = row.get("pnl", "")
            if not pnl_str:
                continue
            try:
                pnl = float(pnl_str)
            except (ValueError, TypeError):
                continue

            amount = float(row.get("amount", 10.0))
            entry_str = row.get("entry_tick", "")
            exit_str = row.get("exit_tick", "")
            entry_tick = int(entry_str) if entry_str else None
            exit_tick = int(exit_str) if exit_str else None

            positions.append(FakePosition(
                pnl=pnl,
                exit_reason=row.get("exit_reason", "unknown") or "unknown",
                entry_tick=entry_tick,
                exit_tick=exit_tick,
                amount=amount,
            ))

    if not positions:
        print("❌ No valid trades found in CSV.", file=sys.stderr)
        sys.exit(1)

    return positions


def generate_report(
    positions: list[FakePosition],
    initial_balance: float,
    asset: str | None = None,
    window: str | None = None,
) -> dict:
    """Run PostTradeAnalyzer and return a serializable report dict."""
    analyzer = PostTradeAnalyzer()
    report = analyzer.analyze(positions, initial_balance=initial_balance)

    out = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "asset": asset or "unknown",
        "window": window or "unknown",
        "initial_balance": initial_balance,
        "post_trade": report.to_dict(),
    }

    return out


def print_summary(report_dict: dict) -> None:
    """Print a human-readable summary to stdout."""
    s = report_dict["post_trade"]["summary"]

    print("\n" + "═" * 60)
    print(f"  POST-TRADE ANALYTICS — {report_dict['asset']} {report_dict['window']}")
    print("═" * 60)
    print(f"  Initial balance:  ${report_dict['initial_balance']:.2f} USDC")
    print(f"  Total trades:     {s['total_trades']}")
    print(f"  Total PnL:        {s['total_pnl']:+.4f} USDC ({s['total_pnl_pct']:+.2%})")
    print()
    print(f"  Expectancy:       {s['expectancy']:+.4f} USDC/trade ({s['expectancy_pct']:+.2%})")
    print(f"  Win Rate:         {s['win_rate']:.1%} ({s['winners']}W / {s['losers']}L)")
    print(f"  Profit Factor:    {s['profit_factor']:.2f}")
    print()
    print(f"  Best Trade:       {s['best_trade']:+.4f} USDC")
    print(f"  Worst Trade:      {s['worst_trade']:+.4f} USDC")
    print(f"  Avg Winner:       {s['avg_winner']:+.4f} USDC")
    print(f"  Avg Loser:        {s['avg_loser']:+.4f} USDC")
    print()
    print(f"  Max Drawdown:     {s['max_drawdown']:.2%}")
    print(f"  Max Consec Loss:  {s['max_consecutive_losses']}")
    print(f"  Max Consec Wins:  {s['max_consecutive_wins']}")
    print(f"  Sharpe Estimate:  {s['sharpe_estimate']:.3f}")
    print()
    print(f"  Best Exit Reason: {s['best_exit_reason']}")
    print(f"  Worst Exit Reason:{s['worst_exit_reason']}")
    print()
    print("  Exit Reason Breakdown:")
    by_reason = report_dict["post_trade"].get("by_exit_reason", [])
    for r in by_reason:
        print(
            f"    {r['reason']:<20} "
            f"count={r['count']:>4}  "
            f"pnl={r['total_pnl']:>+8.4f}  "
            f"avg={r['avg_pnl']:>+7.4f}  "
            f"wr={r['win_rate']:.1%}  "
            f"pct={r['pct_of_trades']:.0f}%"
        )
    print("═" * 60 + "\n")


def main():
    args = parse_args()

    if not args.input:
        print("❌ --input is required. Use --help for usage.", file=sys.stderr)
        sys.exit(1)

    path = args.input
    ext = path.rsplit(".", 1)[-1].lower() if "." in path else ""

    if ext == "json":
        positions = load_from_json(path)
    elif ext == "csv":
        positions = load_from_csv(path)
    else:
        print(f"❌ Unsupported format: {ext}. Use .json or .csv", file=sys.stderr)
        sys.exit(1)

    report = generate_report(
        positions,
        initial_balance=args.balance,
        asset=args.asset,
        window=args.window,
    )

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            json.dump(report, f, indent=2, default=str)
        print(f"\n💾 Post-trade report saved to: {out_path}")
    else:
        # Print to stdout
        print_summary(report)
        # Also output JSON to stdout if piped
        if not sys.stdout.isatty():
            json.dump(report, sys.stdout, indent=2, default=str)


if __name__ == "__main__":
    main()
