# monitoring/grafana/datasources/prometheus.yml
#
# Provisioning del datasource Prometheus para Grafana.
# Lo monta docker-compose en /etc/grafana/provisioning/datasources.

apiVersion: 1

datasources:
  - name:      Prometheus
    type:      prometheus
    access:    proxy
    url:       http://prometheus:9090
    isDefault: true
    editable:  false
